---
version: '0.2.0'
frames_per_town: 3
weather_update_frequency: 30
sequence_start: 60
towns:
  - 1
  - 2
spawn_points:
  - 23
  - 46
lidar_extrinsics:
  x: 0.0
  y: 0.0
  z: 1.80
  pitch: 0.0
  yaw: 180.0
  roll: 0.0
cameras:
  - id: 0
    width: 1242
    height: 376
    fov: 60   # field of view along width of image
    extrinsics:
      x: [-1.0, 1.0]
      y: [-1.0, 1.0]
      z: [1.70, 1.90]
      pitch: [-5.0, 5.0]
      yaw: [-180.0, 180.0]
      roll: [-5.0, 5.0]
  - id: 1
    width: 1242
    height: 376
    fov: 120
    extrinsics:
      x: [-1.0, 1.0]
      y: [-1.0, 1.0]
      z: [1.70, 1.90]
      pitch: [-5.0, 5.0]
      yaw: [-180.0, 180.0]
      roll: [-5.0, 5.0]
  - id: 2
    width: 1242
    height: 376
    fov: 90
    extrinsics:
      x: [-1.0, 1.0]
      y: [-1.0, 1.0]
      z: [1.70, 1.90]
      pitch: [-5.0, 5.0]
      yaw: [-180.0, 180.0]
      roll: [-5.0, 5.0]
